In [16]:
import numpy as np

class OptimalBST:
    def __init__(self, p, q=None):
        self.p = p
        if q == None:
            q = [0]*(len(p)+1)
        self.q = q
        print('p', p)
        print('q', q)
        self.root = dict()                
                
    def generar_tablas(self, n):
        e = dict()
        w = dict()
        #rellenamos las diagonales con las probabilidades iniciales
        for i in range(1, n + 2):
            e[(i, i - 1)] = self.q[i - 1]
            w[(i, i - 1)] = self.q[i - 1]
        for l in range(1, n + 1):
            for i in range(1, n - l + 2):
                j = i + l - 1
                e[(i, j)] = float("inf")
                w[(i, j)] = w[(i, j - 1)] + self.p[j - 1] + self.q[j]
                for r in range(i, j + 1):
                    t = round(e[(i, r - 1)] + e[(r + 1, j)] + w[(i, j)], 2)
                    if t < e[(i, j)]:
                        e[(i, j)] = t
                        self.root[(i, j)] = r
                        print()
                        print('l', l, ' i', i, ' j', j, ' r', r)
                        self.imprimir(w, n)
                        self.imprimir(e, n)
                        self.imprimir(self.root, n)
        
        print()
        print('*****************************')
        print('RESULTADO FINAL')
        print('w --> probabilidades')
        self.imprimir(w, n)        
        print('e --> costes')
        self.imprimir(e, n)  
        print('root --> raices')
        self.imprimir(self.root, n)        
        #return e

    def imprimir(self, datos, longitud):
        matriz = np.zeros((longitud+1, longitud+1))
        for fila, columna in datos:
            matriz[fila-1][columna-1] = datos[fila, columna] 
        print(matriz)        
        print()

    def camino(self):
        raiz = self.root[(1, len(self.p))]
        print ("k[%d] is the root" % raiz)
        izquierdo, derecho = [(1, raiz - 1,)], [(raiz + 1, len(self.p),)]
        p = [raiz]
        while p:            
            if izquierdo:
                i, j = izquierdo.pop(0)
                if j < i:
                    print ("d[%d] is the left child of k[%d]" % (j, p[0]))
                else:
                    raiz = self.root[(i, j)]
                    print ("k[%d] is the left child of k[%d]" % (raiz, p[0]))
                    p[:0] = [raiz]
                    izquierdo.insert(0, (i, raiz - 1,))
                    derecho.insert(0, (raiz + 1, j))                
            else:
                i, j = derecho.pop(0)
                if j < i:
                    print ("d[%d] is the right child of k[%d]" % (j, p.pop(0)))
                else:
                    raiz = self.root[(i, j)]
                    print ("k[%d] is the right child of k[%d]" % (raiz, p.pop(0)))
                    p[:0] = [raiz]
                    izquierdo.insert(0, (i, raiz - 1))
                    derecho.insert(0, (raiz + 1, j))        


In [17]:
#p = [0.15, 0.10, 0.05, 0.10, 0.20]
#q = [0.05, 0.10, 0.05, 0.05, 0.05, 0.10]
p= [0.2, 0.35, 0.05, 0.1, 0.3]
q=None
bst = OptimalBST(p, q)
bst.generar_tablas(len(p))
print('*********************************')
bst.camino()
#print('*********************************')


p [0.2, 0.35, 0.05, 0.1, 0.3]
q [0, 0, 0, 0, 0, 0]

l 1  i 1  j 1  r 1
[[ 0.2  0.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0.   0. ]]

[[ 0.2  0.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0.   0. ]]

[[ 1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]]


l 1  i 2  j 2  r 2
[[ 0.2   0.    0.    0.    0.    0.  ]
 [ 0.    0.35  0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.    0.    0.  ]]

[[ 0.2   0.    0.    0.    0.    0.  ]
 [ 0.    0.35  0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.    0.  