In [8]:
import numpy as np
size = 4
ma = np.full((size,size), 9999)
p = np.full((size,size), '_')
letras = {0: 'A', 1: 'B', 2: 'C', 3:'D', 4:'E' }


ma[0,1]  = 14
ma[1,2]  = 11
ma[1,3]  = 13
ma[2,0]  = 5
ma[2,1]  = 10
ma[3,2]  = 16

print('inicial')
print(ma)
print('**************')
print()      
        
for k in range(0,size):    
    for i in range(0,size):
        for j in range(0,size):
            if ma[i,j] > ma[i,k] + ma[k,j]:                
                ma[i,j] = ma[i,k] + ma[k,j]
                p[i,j] = letras[k]
                #print('k', k, ' i', i, ' j',j)                
                #print(ma)
                #print('**************')
                #print()
    
    print('k', k)
    print(ma)
    print()
    print(p)
    print('**************')
                                            

print(ma)
print('**************')
print(p)

inicial
[[9999   14 9999 9999]
 [9999 9999   11   13]
 [   5   10 9999 9999]
 [9999 9999   16 9999]]
**************

k 0
[[9999   14 9999 9999]
 [9999 9999   11   13]
 [   5   10 9999 9999]
 [9999 9999   16 9999]]

[['_' '_' '_' '_']
 ['_' '_' '_' '_']
 ['_' '_' '_' '_']
 ['_' '_' '_' '_']]
**************
k 1
[[9999   14   25   27]
 [9999 9999   11   13]
 [   5   10   21   23]
 [9999 9999   16 9999]]

[['_' '_' 'B' 'B']
 ['_' '_' '_' '_']
 ['_' '_' 'B' 'B']
 ['_' '_' '_' '_']]
**************
k 2
[[30 14 25 27]
 [16 21 11 13]
 [ 5 10 21 23]
 [21 26 16 39]]

[['C' '_' 'B' 'B']
 ['C' 'C' '_' '_']
 ['_' '_' 'B' 'B']
 ['C' 'C' '_' 'C']]
**************
k 3
[[30 14 25 27]
 [16 21 11 13]
 [ 5 10 21 23]
 [21 26 16 39]]

[['C' '_' 'B' 'B']
 ['C' 'C' '_' '_']
 ['_' '_' 'B' 'B']
 ['C' 'C' '_' 'C']]
**************
[[30 14 25 27]
 [16 21 11 13]
 [ 5 10 21 23]
 [21 26 16 39]]
**************
[['C' '_' 'B' 'B']
 ['C' 'C' '_' '_']
 ['_' '_' 'B' 'B']
 ['C' 'C' '_' 'C']]
