In [1]:
def orden_optimo_producto (d):    
    n= len (d) -1
    m =[[0 for i in range (n +1) ] for i in range (n+1) ]
    # recorremos las diagonales , desde s=1 hasta s=n -1
    for s in range (1 ,n):
        for i in range (1 ,n-s +1) :
        # optimizacion del parentizado para m[i][i+s]
            for k in range (i,i+s):
                n_prod = m[i][k] + m[k +1][ i+s] + d[i -1]* d[k]*d[i+s]
                if k==i or n_prod < minimo :
                    minimo = n_prod
            m[i][i+s]= minimo        
    return m #resultado esta en m [1][ n]

In [2]:
#Para las matrices 9x7(m1) 7x7(m2) 7x2(m3) 2x4(m4) 4x6(m5)
d = [9,7,7,2,4,6]

a = orden_optimo_producto(d)

print(a)
print(a[1][len(d)-1])

[[0, 0, 0, 0, 0, 0], [0, 0, 441, 224, 296, 380], [0, 0, 0, 98, 154, 230], [0, 0, 0, 0, 56, 132], [0, 0, 0, 0, 0, 48], [0, 0, 0, 0, 0, 0]]
380


In [36]:
import numpy as np

def gk(i,j):
    return str(i)+','+str(j)

def matrix_chain_order(p):
    n = len(p)-1
    m,s = {}, {}
    s = {}    
    m =[[0 for i in range (n +1) ] for i in range (n+1) ]
    for i in range(1, n+1):        
        m[i][i]=0
    for l in range(2, n+1):
        for i in range(1, n-l+2):
            j = i+l-1            
            m[i][j] = -1
            for k in range(i, j):    
                print('l', l, ' i', i, ' j', j, ' k', k)
                q = m[i][k] + m[k+1][j] + p[i-1]*p[k]*p[j]  
                print('q = ', m[i][k], '+', m[k+1][j], '+(',p[i-1],'*',p[k],'*',p[j],') = ', q)
                if q<m[i][j] or m[i][j] < 0:  
                    print('nuevo valor para m[',i,',',j,']')                    
                    m[i][j]=q
                    s[gk(i, j)] = k
        print()        
        print(np.array(m))
        print()
    return m, s

def imprimir(datos):
    longitud = len(datos)
    matriz = np.zeros((longitud+1, longitud+1))
    for fila, columna in datos:
        matriz[fila-1][columna-1] = datos[fila, columna] 
    print(matriz)        
    print()

def get_optimal_parens(s, i, j):
    res = ''
    if i == j:
        return "M_"+str(j)
    else:
        res += "("
        res += get_optimal_parens(s, i, s[gk(i, j)])+"*"
        res += get_optimal_parens(s, s[gk(i, j)]+1, j)
        res +=  ")"
        return res

In [37]:
d = [9,7,7,2,4,6]

m, s = matrix_chain_order(d)

print('********')
print('RESULTADO')
print(np.array(m))
print('********')
print(s)
print('********')
print('multiplicaciones necesarias')
print(m[1][len(d)-1])

print('formula en texto')
texto = get_optimal_parens(s, 1, len(d)-1)
print(texto[1:len(texto)-1])

l 2  i 1  j 2  k 1
q =  0 + 0 +( 9 * 7 * 7 ) =  441
nuevo valor para m[ 1 , 2 ]
l 2  i 2  j 3  k 2
q =  0 + 0 +( 7 * 7 * 2 ) =  98
nuevo valor para m[ 2 , 3 ]
l 2  i 3  j 4  k 3
q =  0 + 0 +( 7 * 2 * 4 ) =  56
nuevo valor para m[ 3 , 4 ]
l 2  i 4  j 5  k 4
q =  0 + 0 +( 2 * 4 * 6 ) =  48
nuevo valor para m[ 4 , 5 ]

[[  0   0   0   0   0   0]
 [  0   0 441   0   0   0]
 [  0   0   0  98   0   0]
 [  0   0   0   0  56   0]
 [  0   0   0   0   0  48]
 [  0   0   0   0   0   0]]

l 3  i 1  j 3  k 1
q =  0 + 98 +( 9 * 7 * 2 ) =  224
nuevo valor para m[ 1 , 3 ]
l 3  i 1  j 3  k 2
q =  441 + 0 +( 9 * 7 * 2 ) =  567
l 3  i 2  j 4  k 2
q =  0 + 56 +( 7 * 7 * 4 ) =  252
nuevo valor para m[ 2 , 4 ]
l 3  i 2  j 4  k 3
q =  98 + 0 +( 7 * 2 * 4 ) =  154
nuevo valor para m[ 2 , 4 ]
l 3  i 3  j 5  k 3
q =  0 + 48 +( 7 * 2 * 6 ) =  132
nuevo valor para m[ 3 , 5 ]
l 3  i 3  j 5  k 4
q =  56 + 0 +( 7 * 4 * 6 ) =  224

[[  0   0   0   0   0   0]
 [  0   0 441 224   0   0]
 [  0   0   0  98 154   0]
 [  0

In [85]:
d = [66, 87, 71, 43, 18, 19, 33, 98, 54]

m, s = matrix_chain_order(d)

print(m)
print('********')
print(s)
print('*****************')
print(m[1][len(d)-1])
texto = get_optimal_parens(s, 1, len(d)-1)
print(texto[1:len(texto)-1])

cosa:  [1, 2, 3, 4, 5, 6, 7, 1, 2, 3, 4, 5, 6, 6, 7, 1, 2, 3, 4, 4, 5, 7, 1, 4, 2, 4, 3, 4, 4, 1, 4, 2, 3, 4, 3, 4, 1, 3, 4, 2, 4, 1, 4]
[[0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 407682, 512517, 269496, 292068, 319986, 455418, 498402], [0, 0, 0, 265611, 166140, 190076, 229104, 389106, 415458], [0, 0, 0, 0, 54954, 72713, 108414, 249696, 288720], [0, 0, 0, 0, 0, 14706, 36828, 145350, 206550], [0, 0, 0, 0, 0, 0, 11286, 69498, 164754], [0, 0, 0, 0, 0, 0, 0, 61446, 161994], [0, 0, 0, 0, 0, 0, 0, 0, 174636], [0, 0, 0, 0, 0, 0, 0, 0, 0]]
********
{'1,3': 1, '3,6': 4, '6,8': 7, '2,7': 4, '1,7': 4, '1,2': 1, '5,6': 5, '4,6': 4, '1,8': 4, '2,3': 2, '1,6': 4, '4,7': 4, '3,4': 3, '6,7': 6, '2,6': 4, '1,4': 1, '1,5': 4, '2,8': 4, '4,8': 4, '4,5': 4, '3,5': 3, '3,7': 4, '2,4': 2, '2,5': 2, '3,8': 4, '5,8': 7, '7,8': 7, '5,7': 6}
*****************
498402
(M_1*(M_2*(M_3*M_4)))*(((M_5*M_6)*M_7)*M_8)


In [88]:
d ={}
d[1,2] = 25
print(d)

{(1, 2): 25}
